services:
  base-image:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: dockerfile-base
  real-bot:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: dockerfile-final
      no_cache: true
    depends_on:
      - base-image
    env_file:
      - .env

